---

- name: Create the application user
  user: name={{ web_user }} state=present

- name: Create the application group
  group: name={{ web_group }} system=yes state=present

- name: Add the application user to the application group
  user: name={{ web_user }} group={{ web_group }} state=present